name: Build and deploy 

on:
  push:
    branches:
      -  main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker Image
        run: mvn docker:build